Repository lihenggui/blocker, pull requests merged in 2023-10, with the labels that each got.

#412 Fix #404: Use targetPage as the key to avoid jumping to wrong tab
  feature/appdetail/src/main/kotlin/com/merxury/blocker/feature/appdetail/AppDetailScreen.kt
  feature/appdetail/src/main/kotlin/com/merxury/blocker/feature/appdetail/AppDetailViewModel.kt
Labels: bug

#433 Upgrade Android Gradle plugin to 8.3.0-alpha09
  gradle/libs.versions.toml
Labels: version update

#444 Pull refresh
  feature/appdetail/build.gradle.kts
  feature/appdetail/src/main/kotlin/com/merxury/blocker/feature/appdetail/AppDetailScreen.kt
  feature/appdetail/src/main/kotlin/com/merxury/blocker/feature/appdetail/AppDetailViewModel.kt
  feature/applist/build.gradle.kts
  feature/applist/src/androidTest/kotlin/com/merxury/blocker/feature/applist/AppListScreenTest.kt
  feature/applist/src/main/kotlin/com/merxury/blocker/feature/applist/AppListScreen.kt
  feature/applist/src/main/kotlin/com/merxury/blocker/feature/applist/AppListViewModel.kt
  feature/applist/src/test/kotlin/com/merxury/blocker/feature/applist/AppListScreenScreenshotTests.kt
Labels: enhancement, feature
